name: "Prochy's AniList"
guid: "666225e2-ef4a-4f89-9a7d-5050a816b1f5"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 12
targetAbi: "10.10.7.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  ### New features and improvements ###
  - season and episode provider
  - rate limiting
